"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""



from pathlib import Path

# 追記
import os
from datetime import timedelta
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  #  今のファイルの場所から2階層上（backend）のパスを取得。つまり：backend フォルダのパス。


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/



# ----追記 .envから読み込む----
load_dotenv()
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
DEBUG = os.getenv("DJANGO_DEBUG") == "True"

ALLOWED_HOSTS = os.getenv(
    "DJANGO_ALLOWED_HOSTS",
    ""
).split(",")

CORS_ORIGIN_WHITELIST = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    ""
).split(",")



# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 追記
    # 外部パッケージ
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'djoser',   # ユーザー認証まわりをほぼ全部用意してくれるライブラリ



    # 自作アプリ
    'users',
    'videos',
]



# 追記
DJOSER = {
    'LOGIN_FIELD': 'email',
    'USER_CREATE_PASSWORD_RETYPE': True,   # 任意。登録時にパスワード確認を追加できる
    'SERIALIZERS': {
        'user_create': 'users.serializers.UserSerializer',  # カスタムUserSerializerを使う
        'user': 'users.serializers.UserSerializer',
    },
}



# 追記  Django で「独自のユーザーモデルを使うときに必要になる設定」。
AUTH_USER_MODEL = 'users.User'  #  Django、ユーザーモデルは users アプリ内の User クラスを使う。


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # 追記
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# 追記  Reactなど他ドメインからのAPIアクセスを許可する
# CORS_ORIGIN_WHITELIST = [
#     "http://localhost:3000",
#     "http://localhost:5173",
# ]


ROOT_URLCONF = 'youtube_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'youtube_project.wsgi.application'


# 追記  API にアクセスするためのルール（誰が・どうやってアクセスできるか）を定める設定
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # 全ての API がログイン必須 になる。
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT（JSON Web Token）を使って認証するという意味。
    ],
}


# 追記 「JWT認証トークンのルール」を細かく設定
SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('Bearer',), # これは、HTTPリクエストのヘッダーで、どんな形式でトークンを送るかを指定する。
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30000), # JWTのアクセストークンの有効期限。
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'


# 追記
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # アップロードされたファイルを保存する場所（フォルダ）。backend/media/というフォルダを作って、そこに画像や動画を保存するという意味。
MEDIA_URL = '/media/'  # フロント側からアクセスするときのURLの頭部分（パス）。http://localhost:8000/media/xxx.jpg
