# Generated by Django 5.1.3 on 2026-01-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_cover_image_url_user_profile_icon_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cover_image_url',
        ),
    ]
